# Clone location
clone_folder: c:\language-rust

# Add new environments to the build here:
environment:
  matrix:
    # - resolver: lts-6.35 # ghc-7.10.3
    # - resolver: lts-7.24 # ghc-8.0.1
    # - resolver: lts-9.21 # ghc-8.0.2
    - resolver: lts-11.22 # ghc-8.2.2
    - resolver: lts-12.14 # ghc-8.4.4
    - resolver: lts-14.4  # ghc-8.6.5
    - resolver: nightly

# Manually fetch stack
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl --output stack.zip --location --insecure http://www.stackage.org/stack/windows-x86_64
  - dir
  - 7z x stack.zip stack.exe
  - stack --no-terminal init --resolver %resolver% > nul
  - stack --no-terminal setup --resolver %resolver% > nul

# Install Happy and Alex first, before installing
build_script:
  - stack --no-terminal install --resolver %resolver% happy-1.19.12
  - stack --no-terminal install --resolver %resolver% alex

test_script:
  - stack --no-terminal test --resolver %resolver% :unit-tests --test-arguments "--plain"

